
    
         id="americana-sp" class="elementor-tab-title eael-accordion-header show-this active" tabindex="0" data-tab="1" aria-controls="elementor-tab-content-2461" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">AMERICANA - SP</span> id="elementor-tab-content-2461" class="eael-accordion-content clearfix" data-tab="1" aria-labelledby="americana-sp" style="display: block;"><p>Av Campos Sales, 991 – Sala 12 – Jardim Girassol – CEP 13465 – 590</p>
    
         id="araraquara-sp" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="2" aria-controls="elementor-tab-content-2462" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">ARARAQUARA - SP</span> id="elementor-tab-content-2462" class="eael-accordion-content clearfix" data-tab="2" aria-labelledby="araraquara-sp" style="display: none;"><p>Rua Antonia de Camargo Abreu, 51 Sala 74 – 7º andar – Vila Velosa, Araraquara – SP, 14806-050</p>
    
         id="atibaia-sp" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="3" aria-controls="elementor-tab-content-2463" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">ATIBAIA - SP</span> id="elementor-tab-content-2463" class="eael-accordion-content clearfix" data-tab="3" aria-labelledby="atibaia-sp" style="display: none;"><p>Rua José Alvim, 42 – Sala 11 – Piso 2 – Centro, Atibaia – SP, 12970-750</p>
    
         id="batatais-sp" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="4" aria-controls="elementor-tab-content-2464" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">BATATAIS - SP</span> id="elementor-tab-content-2464" class="eael-accordion-content clearfix" data-tab="4" aria-labelledby="batatais-sp" style="display: none;"><p style="font-weight: 400;">Claretiano de Batatais – Rua Dom Bosco, 466 Dentro do CEUCLAR – Centro Universitário – Parque Castelo, Batatais – SP, 14300-000</span style="font-weight: 400;"><br></span style="font-weight: 400;">Horário de atendimento: 9h às 16h</span></p>
    
         id="barueri-sp" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="5" aria-controls="elementor-tab-content-2465" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">BARUERI - SP</span> id="elementor-tab-content-2465" class="eael-accordion-content clearfix" data-tab="5" aria-labelledby="barueri-sp" style="display: none;"><p>R. Benedita Guerra Zendron, 57 – Vila Sao Joao, Barueri – SP, 06401-190</p>
    
         id="bauru-sp" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="6" aria-controls="elementor-tab-content-2466" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">BAURU - SP</span> id="elementor-tab-content-2466" class="eael-accordion-content clearfix" data-tab="6" aria-labelledby="bauru-sp" style="display: none;"><p>Rua Luso Brasileira, 4-44 sala702 Jardim Estoril. cep: 17016-230 Bauru S.P</p>
    
         id="barretos-sp" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="7" aria-controls="elementor-tab-content-2467" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">BARRETOS - SP</span> id="elementor-tab-content-2467" class="eael-accordion-content clearfix" data-tab="7" aria-labelledby="barretos-sp"><p style="font-weight: 400;">Av. 29, 1131, Centro CEP 14780-350 – Barretos/SP</span></p><p style="font-weight: 400;">Atendimento de Segunda a Sexta das 09:00 às 16:00</span></p>
    
         id="botucatu-sp" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="8" aria-controls="elementor-tab-content-2468" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">BOTUCATU - SP</span> id="elementor-tab-content-2468" class="eael-accordion-content clearfix" data-tab="8" aria-labelledby="botucatu-sp"><p style="font-weight: 400;">Rua: 7 de Setembro, 10 -A lado, cep: 18603-340- Jardim Central/</span></p><p style="font-weight: 400;">Horário: das 9h as 12h e das 13h30 as 16h</span></p>
    
         id="bragana-paulista-sp" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="9" aria-controls="elementor-tab-content-2469" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">BRAGANÇA PAULISTA - SP</span> id="elementor-tab-content-2469" class="eael-accordion-content clearfix" data-tab="9" aria-labelledby="bragana-paulista-sp"><p>Rua São Francisco de Assis, 218, sala 10 – Predio central JD São José – Bragança Paulista – CEP 12.916-350</p>
    
         id="caapava-sp" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="10" aria-controls="elementor-tab-content-24610" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">CAÇAPAVA - SP</span> id="elementor-tab-content-24610" class="eael-accordion-content clearfix" data-tab="10" aria-labelledby="caapava-sp"><p>R. Tenente Mesquita, 211 – Vila Pantaleão, Caçapava – SP, 12280-048<br>Atendimento de Segunda a Sexta das 09:00 às 16:00</p>
    
         id="caieiras-sp" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="11" aria-controls="elementor-tab-content-24611" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">CAIEIRAS - SP</span> id="elementor-tab-content-24611" class="eael-accordion-content clearfix" data-tab="11" aria-labelledby="caieiras-sp">Av. Prof Carvalho Pinto, 207 – Jardim Santo Antônio, Caieiras – 0770-000
            Atendimento de Segunda a Sexta das 09:00 às 16:00
    
         id="campinas-sp" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="12" aria-controls="elementor-tab-content-24612" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">CAMPINAS - SP</span> id="elementor-tab-content-24612" class="eael-accordion-content clearfix" data-tab="12" aria-labelledby="campinas-sp"><p>Avenida Barão de Itapura, 2.294 – 13º andar – Sala 131 – Condomínio Edif. Montpellier – CEP: 13073-300 – Jd. Guanabara – Campinas/SP</p>
    
         id="franca-sp" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="13" aria-controls="elementor-tab-content-24613" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">FRANCA - SP</span> id="elementor-tab-content-24613" class="eael-accordion-content clearfix" data-tab="13" aria-labelledby="franca-sp"><p>Av. Sete de Setembro, 500 – Res. Baldassari, Franca – SP, 14401-278 9° andar sala 904</p>
    
         id="hortolndia-sp" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="14" aria-controls="elementor-tab-content-24614" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">HORTOLÂNDIA - SP</span> id="elementor-tab-content-24614" class="eael-accordion-content clearfix" data-tab="14" aria-labelledby="hortolndia-sp"><p>Rua Amélia Camargo Bluemer, 100 – Loteamento Remanso Campineiro – CEP 13184 – 440</p>
    
         id="indaiatuba-sp" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="15" aria-controls="elementor-tab-content-24615" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">INDAIATUBA - SP</span> id="elementor-tab-content-24615" class="eael-accordion-content clearfix" data-tab="15" aria-labelledby="indaiatuba-sp"><p>Dentro da Faculdade Max Planck – Av. 9 de Dezembro, 460 – Jd. Leonor – CEP: 13343-060 – Indaiatuba/SP</p>
    
         id="ja-sp" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="16" aria-controls="elementor-tab-content-24616" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">JAÚ - SP</span> id="elementor-tab-content-24616" class="eael-accordion-content clearfix" data-tab="16" aria-labelledby="ja-sp"><p>Av. do Café, 250 – Vila Netinho Prado, Jaú – SP, 17208-010</p>
    
         id="jundia-sp" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="17" aria-controls="elementor-tab-content-24617" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">JUNDIAÍ - SP</span> id="elementor-tab-content-24617" class="eael-accordion-content clearfix" data-tab="17" aria-labelledby="jundia-sp"><p>Endereço: R. Barão de Teffé, no 1.000 – Sala 91 – Jardim Ana Maria, Jundiaí – SP, 13208-761</p>
    
         id="lorena-sp" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="18" aria-controls="elementor-tab-content-24618" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">LORENA - SP</span> id="elementor-tab-content-24618" class="eael-accordion-content clearfix" data-tab="18" aria-labelledby="lorena-sp"><p>UNISAL – Centro Salesiano Universitário de São Paulo – R. Dom Bôsco, 284 – Centro, Lorena – SP, 12600-100<br>Atendimento de Segunda a Sexta das 09:00 às 16:00</p>
    
         id="ituverava-sp" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="19" aria-controls="elementor-tab-content-24619" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">ITUVERAVA - SP</span> id="elementor-tab-content-24619" class="eael-accordion-content clearfix" data-tab="19" aria-labelledby="ituverava-sp"><p style="font-weight: 400;">Av. Dr. José Aníbal Soares de Oliveira, 938 – Pouso Alto, Ituverava – SP, 14500-000</span></p><p style="font-weight: 400;">Horário de atendimento : 9h 12h –&nbsp; 13h 16h </span></p>
    
         id="marlia-sp-jardim-tangar" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="20" aria-controls="elementor-tab-content-24620" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">MARÍLIA - SP (Jardim Tangará)</span> id="elementor-tab-content-24620" class="eael-accordion-content clearfix" data-tab="20" aria-labelledby="marlia-sp-jardim-tangar"><p>Av. das Esmeraldas, 821 – sala 704, Complexo Empresarial Villas Boas, Bairro: Jardim Tangará, Marília/S.P. CEP: 17.516-000</p>
    
         id="marlia-sp-andradina" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="21" aria-controls="elementor-tab-content-24621" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">MARÍLIA - SP (Andradina)</span> id="elementor-tab-content-24621" class="eael-accordion-content clearfix" data-tab="21" aria-labelledby="marlia-sp-andradina"><p>Rua Paes Leme, nº 1598, Sala 2, Centro, CEP 16901-010, Andradina. PA Andradina – Unidade Marília</p>
    
         id="marlia-sp-araatuba" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="22" aria-controls="elementor-tab-content-24622" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">MARÍLIA - SP (Araçatuba)</span> id="elementor-tab-content-24622" class="eael-accordion-content clearfix" data-tab="22" aria-labelledby="marlia-sp-araatuba"><p>R. Maurício de Nassau, 1191 – Santana, Araçatuba – SP, CEP 16050-480, Araçatuba. PA Araçatuba – Unidade Marília</p>
    
         id="mogi-das-cruzes-sp" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="23" aria-controls="elementor-tab-content-24623" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">MOGI DAS CRUZES - SP</span> id="elementor-tab-content-24623" class="eael-accordion-content clearfix" data-tab="23" aria-labelledby="mogi-das-cruzes-sp"><p>Av. Ver. Narciso Yague Guimarães, 1145 – Sala 412 – Jardim Armenia, Mogi das Cruzes – SP, 08780-200</p>
    
         id="mogi-guau-sp-morro-amarelo" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="24" aria-controls="elementor-tab-content-24624" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">MOGI GUAÇU - SP (Morro Amarelo)</span> id="elementor-tab-content-24624" class="eael-accordion-content clearfix" data-tab="24" aria-labelledby="mogi-guau-sp-morro-amarelo"><p>Av. Mogi Mirim, 1249 – Lot. Morro Amarelo, Mogi Guaçu – SP, 13844-110 (Dentro do Prédio Avenida Mall – sala 32)</p>
    
         id="mogi-guau-sp-mococa" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="25" aria-controls="elementor-tab-content-24625" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">MOGI GUAÇU - SP (Mococa)</span> id="elementor-tab-content-24625" class="eael-accordion-content clearfix" data-tab="25" aria-labelledby="mogi-guau-sp-mococa"><p>Avenida Demóstenes P Brasil Pontes, 2131 Dentro da FUNVIC – Jardim Sao Jose, Mococa – SP, 13737-632. PA – Mococa – Unidade Mogi Guaçu</p>
    
         id="osasco-sp" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="26" aria-controls="elementor-tab-content-24626" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">OSASCO - SP</span> id="elementor-tab-content-24626" class="eael-accordion-content clearfix" data-tab="26" aria-labelledby="osasco-sp"><p>Osasco centro Rua: Fiorino Beltrano, 300 Osasco, Centro</p><p>Osasco Norte R. Pres Costa e Silva, 372 Helena Maria</p>
    
         id="ourinhos-sp" class="elementor-tab-title eael-accordion-header" tabindex="0" data-tab="27" aria-controls="elementor-tab-content-24627" class="eael-advanced-accordion-icon-closed"><i aria-hidden="true" class="fa-accordion-icon fas fa-arrow-down"></i></span class="eael-advanced-accordion-icon-opened"><i aria-hidden="true" class="fa-accordion-icon fas fa-minus"></i></span class="eael-accordion-tab-title">OURINHOS - SP</span> id="elementor-tab-content-24627" class="eael-accordion-content clearfix" data-tab="27" aria-labelledby="ourinhos-sp"><p style="font-weight: 400;">Avenida Dr. Altino Arantes, 131 – 3° andar, sala 33 – Centro CEP: 19.900-030</span></p><p style="font-weight: 400;">Horário de atendimento: 9h às 16h&nbsp;</span></p>
    