import type { LiveQuestion } from '../src/types/realtime.ts';

export const liveQuestionsFixture: LiveQuestion[] = [
  {
    id: 'q1',
    type: 'multiple_choice',
    topic: 'Direitos',
    text: 'Qual é um direito do jovem aprendiz?',
    options: [
      { id: 'q1-a', text: 'Férias' },
      { id: 'q1-b', text: 'Trabalho voluntário obrigatório' },
    ],
    correctOptionId: 'q1-a',
    explanation: 'O contrato formal garante férias.',
  },
  {
    id: 'q2',
    type: 'true_false',
    topic: 'Jornada',
    text: 'O jovem aprendiz pode responder apenas uma vez por rodada.',
    options: [
      { id: 'q2-a', text: 'Verdadeiro' },
      { id: 'q2-b', text: 'Falso' },
    ],
    correctOptionId: 'q2-a',
    explanation: 'O servidor bloqueia submissões duplicadas.',
  },
  {
    id: 'q3',
    type: 'multiple_select',
    topic: 'Direitos',
    text: 'Quais itens são direitos do jovem aprendiz?',
    options: [
      { id: 'q3-a', text: 'Carteira assinada' },
      { id: 'q3-b', text: '13º salário' },
      { id: 'q3-c', text: 'Trabalho voluntário obrigatório' },
      { id: 'q3-d', text: 'Férias' },
    ],
    correctOptionIds: ['q3-a', 'q3-b', 'q3-d'],
    explanation: 'O contrato de aprendizagem garante registro, 13º salário e férias.',
  },
  {
    id: 'q4',
    type: 'poll',
    topic: 'Interesses',
    text: 'Qual tema você quer aprofundar?',
    options: [
      { id: 'q4-a', text: 'Currículo' },
      { id: 'q4-b', text: 'Entrevista' },
      { id: 'q4-c', text: 'Direitos' },
    ],
    explanation: 'A enquete orienta o próximo assunto.',
  },
  {
    id: 'q5',
    type: 'word_cloud',
    topic: 'Carreira',
    text: 'O que mais importa no primeiro emprego?',
    options: [],
    explanation: 'As respostas parecidas são agrupadas.',
  },
  {
    id: 'q6',
    type: 'scale',
    topic: 'Confiança',
    text: 'De 1 a 5, quão confiante você está?',
    options: [],
    scale: {
      min: 1,
      max: 5,
      step: 1,
      minLabel: 'Pouco confiante',
      maxLabel: 'Muito confiante',
    },
    explanation: 'A escala mostra a média do grupo.',
  },
  {
    id: 'q7',
    type: 'ranking',
    topic: 'Prioridades',
    text: 'Ordene suas prioridades.',
    options: [
      { id: 'q7-a', text: 'Aprendizado' },
      { id: 'q7-b', text: 'Ambiente' },
      { id: 'q7-c', text: 'Salário' },
    ],
    explanation: 'A agregação usa contagem Borda simples.',
  },
  {
    id: 'q8',
    type: 'qna',
    topic: 'Plano de acao',
    text: 'Qual primeiro passo voce faria esta semana?',
    options: [],
    explanation: 'Respostas equivalentes sao agrupadas.',
  },
];
